language: c
sudo: true
compiler: clang
dist: trusty
services: docker

addons:
  apt:
    packages:
    - build-essential
    - automake
    - autoconf-archive
    - pkg-config
    - libtool
    - autoconf
    - autotools-dev
    - gdb
    - valgrind
    - uuid-dev
    - bison
    - flex
    - python-docutils


# now come those components that we need to install via sudo
install:
  - sudo add-apt-repository ppa:adiscon/v8-stable -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq clang
  - sudo apt-get install -qq --force-yes libestr-dev libfastjson-dev liblogging-stdlog-dev

script:
  #- devtools/travis-run-compile-tests.sh
  - export CFLAGS="-g"
  - autoreconf -fvi
  - ./configure --enable-tls
  - make -j2
  - make -j2 check
  - cat tests/test-suite.log
